"""
FlashAIRx 预处理模块
功能: 接收SMILES或3D坐标，生成XTB光谱和分子信息，为GPR预测准备输入
"""

import os
import subprocess
import json
import numpy as np
import pandas as pd
import math
import shutil
from pathlib import Path
from typing import Dict, Optional, Union, Tuple, List
from rdkit import Chem
from rdkit.Chem import AllChem

# ============ 配置 ============
from pathlib import Path
DEFAULT_OUTPUT_DIR = Path.cwd() / "flashairx_temp"

DEFAULT_XTB_PATH = "xtb"
DEFAULT_NPROC = 1
DEFAULT_CHARGE = 0
DEFAULT_MULTIPLICITY = 1
DEFAULT_METHOD = "gfn2"
SPECTRUM_START = 546
SPECTRUM_END = 3846
SPECTRUM_RESOLUTION = 4
LORENTZIAN_WIDTH = 24
SCALE_FACTOR = 0.97


# ============ 分子信息处理 ============

def process_smiles(smiles_string: str) -> Dict:
    """
    处理SMILES字符串：验证有效性、检测官能团、生成3D坐标
    
    参数:
        smiles_string: SMILES字符串
    
    返回:
        dict: {
            'valid': bool,
            'error': str or None,
            'molecule': RDKit Mol object or None,
            'functional_groups': list,
            'xyz_text': str or None,
            'xyz_file': Path or None
        }
    """
    import warnings
    warnings.filterwarnings("ignore", category=UserWarning)
    
    result = {
        'valid': False,
        'error': None,
        'molecule': None,
        'functional_groups': [],
        'xyz_text': None,
        'xyz_file': None
    }
    
    try:
        mol = Chem.MolFromSmiles(smiles_string)
        if mol is None:
            result['error'] = "无效的SMILES字符串"
            return result
        
        mol = Chem.AddHs(mol)
        result['molecule'] = mol
        result['valid'] = True
        
        # 检测官能团
        result['functional_groups'] = detect_functional_groups(mol)
        
        # 生成3D坐标
        xyz_text = generate_3d_coordinates(mol)
        if xyz_text is not None:
            result['xyz_text'] = xyz_text
        
    except Exception as e:
        result['error'] = str(e)
    
    return result


def detect_functional_groups(mol) -> List[str]:
    """检测分子中的官能团"""
    functional_groups = []
    
    fg_patterns = {
        "Alkene": "[CX3]=[C]",
        "Alkyne": "[CX2]#C",
        "Aromatic": "[$([cX3](:*):*),$([cX2+](:*):*)]",
        "Alcohol": "[CX4][OX2H]",
        "Ester": "[CX3](=O)[OX2H0][#6]",
        "Aldehyde": "[CX3H1](=O)[#6]",
        "Ketone": "[#6][CX3](=O)[#6]",
        "Carboxylic Acid": "[CX3](=O)[OX1H0-,X2H1]",
        "Ether": "[OX2;!$(OC=O)]([#6])[#6]",
        "Amide": "[CX3](=[OX1])[NX3H2,NX3H1,NX3H0,NX4H]",
        "Amine": "[NX3;H2,H1,H0;!$(NC=O);!$(CN=O)]",
        "Nitrile": "[NX1]#[CX2]",
        "Nitro": "[$([NX3](=O)=O),$([NX3+](=O)[O-])][!#8]",
        "Imine": "[CX3]=[NX2]"
    }
    
    found_fgs = False
    for fg_name, pattern in fg_patterns.items():
        pattern_mol = Chem.MolFromSmarts(pattern)
        if pattern_mol is not None:
            if mol.GetSubstructMatches(pattern_mol):
                functional_groups.append(fg_name)
                found_fgs = True
    
    # 检查是否只包含C和H
    only_c_h = True
    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() not in [1, 6]:
            only_c_h = False
            break
    
    # 如果只包含C和H且没有检测到其他官能团，识别为烷烃
    if only_c_h and not found_fgs:
        functional_groups.append('Alkane')
    
    return functional_groups


def generate_3d_coordinates(mol) -> Optional[str]:
    """生成分子的3D坐标，返回XYZ格式文本"""
    try:
        AllChem.EmbedMolecule(mol, AllChem.ETKDG())
        AllChem.UFFOptimizeMolecule(mol)
        
        if mol.GetNumConformers() == 0:
            return None
        
        conformer = mol.GetConformer()
        pt = Chem.GetPeriodicTable()
        
        lines = [str(mol.GetNumAtoms()), "Generated by RDKit"]
        for i in range(mol.GetNumAtoms()):
            pos = conformer.GetAtomPosition(i)
            atom_symbol = pt.GetElementSymbol(mol.GetAtomWithIdx(i).GetAtomicNum())
            lines.append(f"{atom_symbol} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
        
        return "\n".join(lines)
        
    except Exception:
        return None


def get_molecule_info(smiles_string: str) -> Dict:
    """获取分子基本信息（不生成3D坐标）"""
    mol = Chem.MolFromSmiles(smiles_string)
    if mol is None:
        return {'inchikey': None, 'functional_groups': []}
    
    mol = Chem.AddHs(mol)
    inchikey = Chem.MolToInchiKey(mol)
    functional_groups = detect_functional_groups(mol)
    
    return {
        'inchikey': inchikey.replace("-", "_") if inchikey else None,
        'functional_groups': functional_groups,
        'functional_groups_sorted': tuple(sorted(functional_groups))
    }


# ============ 3D坐标处理 ============

def parse_xyz_file(xyz_file: Path) -> Tuple[List[str], List[float], List[float], List[float]]:
    """
    解析XYZ文件
    
    返回:
        (elements, x, y, z)
    """
    elements = []
    x, y, z = [], [], []
    
    with open(xyz_file, 'r') as f:
        lines = f.readlines()
    
    if len(lines) < 3:
        raise ValueError("XYZ文件格式错误")
    
    num_atoms = int(lines[0].strip())
    for line in lines[2:2+num_atoms]:
        parts = line.strip().split()
        if len(parts) >= 4:
            elements.append(parts[0])
            x.append(float(parts[1]))
            y.append(float(parts[2]))
            z.append(float(parts[3]))
    
    return elements, x, y, z


def xyz_to_smiles(xyz_file: Path) -> Optional[str]:
    """从XYZ文件生成SMILES（需要RDKit）"""
    try:
        elements, x, y, z = parse_xyz_file(xyz_file)
        
        # 创建RDKit分子
        mol = Chem.RWMol()
        atom_indices = {}
        
        for i, elem in enumerate(elements):
            atom = Chem.Atom(elem)
            idx = mol.AddAtom(atom)
            atom_indices[i] = idx
        
        # 尝试添加键（基于距离）
        coords = np.column_stack([x, y, z])
        for i in range(len(coords)):
            for j in range(i + 1, len(coords)):
                dist = np.linalg.norm(coords[i] - coords[j])
                # 共价键距离阈值（粗略）
                if dist < 2.0:
                    mol.AddBond(atom_indices[i], atom_indices[j], Chem.BondType.SINGLE)
        
        mol = mol.GetMol()
        Chem.SanitizeMol(mol)
        return Chem.MolToSmiles(mol)
        
    except Exception:
        return None


# ============ XTB计算 ============

def run_xtb_calculation(
    xyz_file_path: Path,
    work_dir: Path,
    nproc: int = DEFAULT_NPROC,
    charge: int = DEFAULT_CHARGE,
    multiplicity: int = DEFAULT_MULTIPLICITY,
    method: str = DEFAULT_METHOD,
    xtb_path: str = DEFAULT_XTB_PATH
) -> Dict:
    """
    运行xTB计算
    
    返回:
        {
            'success': bool,
            'error': str or None,
            'stdout': str,
            'stderr': str
        }
    """
    cmd = [
        xtb_path,
        str(xyz_file_path),
        "--ohess",
        f"--charge={charge}",
        f"--uhf={multiplicity-1}",
        f"--{method}",
        f"--parallel={nproc}"
    ]
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=str(work_dir),
            timeout=3600
        )
        
        return {
            'success': result.returncode == 0,
            'error': result.stderr if result.returncode != 0 else None,
            'stdout': result.stdout,
            'stderr': result.stderr
        }
        
    except subprocess.TimeoutExpired:
        return {'success': False, 'error': 'XTB计算超时', 'stdout': '', 'stderr': ''}
    except FileNotFoundError:
        return {'success': False, 'error': f'未找到xtb可执行文件: {xtb_path}', 'stdout': '', 'stderr': ''}
    except Exception as e:
        return {'success': False, 'error': str(e), 'stdout': '', 'stderr': ''}


def extract_frequencies_activities(out_file_path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """从g98.out文件提取频率和红外活性"""
    frequencies = []
    activities = []
    
    try:
        with open(out_file_path, 'r') as f:
            lines = f.readlines()
            for i, line in enumerate(lines):
                if 'Frequencies --' in line:
                    freq_line = lines[i].strip().split()[2:]
                    inten_line = lines[i + 3].strip().split()[3:]
                    
                    for freq, act in zip(freq_line, inten_line):
                        frequencies.append(float(freq))
                        activities.append(float(act))
        
        return np.array(frequencies), np.array(activities)
        
    except Exception as e:
        return np.array([]), np.array([])


def generate_ir_spectrum(
    frequencies: np.ndarray,
    activities: np.ndarray,
    start: float = SPECTRUM_START,
    end: float = SPECTRUM_END,
    resolution: float = SPECTRUM_RESOLUTION,
    width: float = LORENTZIAN_WIDTH,
    scale_factor: float = SCALE_FACTOR
) -> Tuple[np.ndarray, np.ndarray]:
    """
    生成红外光谱（Lorentzian展宽）
    
    返回:
        (wavenumber, intensity)
    """
    if len(frequencies) == 0:
        return np.array([]), np.array([])
    
    def lorentzian(x, peak, height, width):
        a = width**2 / 4.0
        return height * a / ((peak - x)**2 + a)
    
    # 校正频率
    freq_scaled = frequencies * scale_factor
    
    # 生成光谱
    numpts = math.ceil((end - start) / resolution)
    wavenumber = np.linspace(start, end, numpts)
    intensity = np.zeros(numpts)
    
    for i, x in enumerate(wavenumber):
        for freq, act in zip(freq_scaled, activities):
            if start <= freq <= end:
                intensity[i] += lorentzian(x, freq, act, width)
    
    # 过滤极小值
    intensity[intensity < 1e-20] = 0.0
    
    return wavenumber, intensity


def extract_xtb_spectrum(work_dir: Path) -> Dict:
    """
    从XTB输出目录提取光谱
    
    返回:
        {
            'wavenumber': np.ndarray,
            'intensity': np.ndarray,
            'csv_file': Path or None,
            'png_file': Path or None
        }
    """
    result = {
        'wavenumber': None,
        'intensity': None,
        'csv_file': None,
        'png_file': None
    }
    
    # 方法1: 从g98.out提取
    out_file = work_dir / "g98.out"
    if out_file.exists():
        freq, act = extract_frequencies_activities(out_file)
        if len(freq) > 0:
            wavenumber, intensity = generate_ir_spectrum(freq, act)
            result['wavenumber'] = wavenumber
            result['intensity'] = intensity
            
            # 保存CSV
            csv_file = work_dir / "xtb_spectrum.csv"
            df = pd.DataFrame({
                'wavenumber': wavenumber,
                'intensity': intensity
            })
            df.to_csv(csv_file, index=False, header=False)
            result['csv_file'] = csv_file
    
    return result


# ============ 归一化函数 ============

def sqrt_norm(data: Union[List, np.ndarray]) -> np.ndarray:
    """平方根归一化"""
    arr = np.array(data, dtype=np.float64)
    min_val = np.sqrt(np.min(arr))
    max_val = np.sqrt(np.max(arr))
    if max_val - min_val < 1e-12:
        return np.zeros_like(arr)
    return (np.sqrt(arr) - min_val) / (max_val - min_val)


# ============ 主预处理函数 ============

def preprocess(
    input_data: Union[str, Path],
    input_type: str = "smiles",
    output_dir: Optional[Path] = None,
    nproc: int = DEFAULT_NPROC,
    charge: int = DEFAULT_CHARGE,
    multiplicity: int = DEFAULT_MULTIPLICITY,
    method: str = DEFAULT_METHOD,
    xtb_path: str = DEFAULT_XTB_PATH,
    keep_temp: bool = True
) -> Dict:
    """
    FlashAIRx预处理主函数
    """
    result = {
        'success': False,
        'error': None,
        'smiles': None,
        'inchikey': None,
        # 'formula': None,  # ✅ 移除 formula
        'functional_groups': [],
        'functional_groups_key': tuple(),
        'work_dir': None,
        'xyz_file': None,
        'optimized_xyz': None,
        'xtb_spectrum': {
            'wavenumber': None,
            'intensity': None,
            'intensity_norm': None,
            'csv_file': None,
        },
        'gpr_input': {
            'X': None,
            'functional_groups': tuple(),
        }
    }
    
    try:
        # ===== 1. 设置输出目录 =====
        if output_dir is None:
            output_dir = Path.cwd() / "flashairx_temp"
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # ===== 2. 处理输入 =====
        if input_type == "smiles":
            smiles_str = str(input_data)
            result['smiles'] = smiles_str
            
            # 获取分子信息
            mol_info = get_molecule_info(smiles_str)
            if mol_info['inchikey'] is None:
                result['error'] = "无效的SMILES字符串"
                return result
            
            result['inchikey'] = mol_info['inchikey']
            # result['formula'] = mol_info['formula']
            result['functional_groups'] = mol_info['functional_groups']
            result['functional_groups_key'] = mol_info['functional_groups_sorted']
            
            # 创建分子工作目录
            work_dir = output_dir / mol_info['inchikey']
            work_dir.mkdir(parents=True, exist_ok=True)
            result['work_dir'] = work_dir
            
            # 生成3D坐标并保存XYZ
            mol_result = process_smiles(smiles_str)
            if not mol_result['valid']:
                result['error'] = mol_result['error']
                return result
            
            xyz_file = work_dir / f"{mol_info['inchikey']}.xyz"
            with open(xyz_file, 'w') as f:
                f.write(mol_result['xyz_text'])
            result['xyz_file'] = xyz_file
            
        elif input_type == "xyz":
            xyz_file = Path(input_data)
            if not xyz_file.exists():
                result['error'] = f"XYZ文件不存在: {xyz_file}"
                return result
            
            # 尝试从XYZ生成SMILES
            smiles_str = xyz_to_smiles(xyz_file)
            if smiles_str:
                result['smiles'] = smiles_str
                mol_info = get_molecule_info(smiles_str)
                if mol_info['inchikey']:
                    result['inchikey'] = mol_info['inchikey']
                    # result['formula'] = mol_info['formula']
                    result['functional_groups'] = mol_info['functional_groups']
                    result['functional_groups_key'] = mol_info['functional_groups_sorted']
                    
                    work_dir = output_dir / mol_info['inchikey']
                    work_dir.mkdir(parents=True, exist_ok=True)
                    
                    # 复制XYZ文件到工作目录
                    shutil.copy2(xyz_file, work_dir / xyz_file.name)
                    result['xyz_file'] = work_dir / xyz_file.name
                    result['work_dir'] = work_dir
                else:
                    # 无法获取分子信息，使用文件名的hash
                    import hashlib
                    file_hash = hashlib.md5(str(xyz_file).encode()).hexdigest()[:8]
                    work_dir = output_dir / f"mol_{file_hash}"
                    work_dir.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(xyz_file, work_dir / xyz_file.name)
                    result['xyz_file'] = work_dir / xyz_file.name
                    result['work_dir'] = work_dir
                    result['functional_groups'] = []
                    result['functional_groups_key'] = tuple()
            else:
                # 无法转换，使用文件名的hash
                import hashlib
                file_hash = hashlib.md5(str(xyz_file).encode()).hexdigest()[:8]
                work_dir = output_dir / f"mol_{file_hash}"
                work_dir.mkdir(parents=True, exist_ok=True)
                shutil.copy2(xyz_file, work_dir / xyz_file.name)
                result['xyz_file'] = work_dir / xyz_file.name
                result['work_dir'] = work_dir
                result['functional_groups'] = []
                result['functional_groups_key'] = tuple()
        
        else:
            result['error'] = f"不支持的输入类型: {input_type}"
            return result
        
        # ===== 3. 运行XTB计算 =====
        xtb_result = run_xtb_calculation(
            xyz_file_path=result['xyz_file'],
            work_dir=result['work_dir'],
            nproc=nproc,
            charge=charge,
            multiplicity=multiplicity,
            method=method,
            xtb_path=xtb_path
        )
        
        if not xtb_result['success']:
            result['error'] = xtb_result['error'] or "XTB计算失败"
            return result
        
        # ===== 4. 提取光谱 =====
        spectrum_result = extract_xtb_spectrum(result['work_dir'])
        
        if spectrum_result['wavenumber'] is not None:
            result['xtb_spectrum']['wavenumber'] = spectrum_result['wavenumber']
            result['xtb_spectrum']['intensity'] = spectrum_result['intensity']
            result['xtb_spectrum']['csv_file'] = spectrum_result['csv_file']
            
            # 归一化
            result['xtb_spectrum']['intensity_norm'] = sqrt_norm(spectrum_result['intensity'])
            
            # 准备GPR输入
            result['gpr_input']['X'] = result['xtb_spectrum']['intensity_norm']
            result['gpr_input']['functional_groups'] = result['functional_groups_key']
        
        # ===== 5. 检查优化后的XYZ =====
        opt_xyz = result['work_dir'] / "xtbopt.xyz"
        if opt_xyz.exists():
            result['optimized_xyz'] = opt_xyz
        
        # ===== 6. 清理临时文件（可选） =====
        if not keep_temp:
            # 保留必要文件，删除中间文件
            for f in result['work_dir'].glob("*.tmp"):
                f.unlink()
        
        result['success'] = True
        return result
        
    except Exception as e:
        result['error'] = str(e)
        return result


# ============ 批量处理 ============

def batch_preprocess(
    input_list: List[Union[str, Path]],
    input_type: str = "smiles",
    output_dir: Optional[Path] = None,
    nproc: int = DEFAULT_NPROC,
    charge: int = DEFAULT_CHARGE,
    multiplicity: int = DEFAULT_MULTIPLICITY,
    method: str = DEFAULT_METHOD,
    xtb_path: str = DEFAULT_XTB_PATH,
    keep_temp: bool = True,
    skip_errors: bool = False
) -> List[Dict]:
    """
    批量预处理
    
    参数:
        input_list: SMILES字符串或XYZ文件路径列表
        input_type: "smiles" 或 "xyz"
        skip_errors: 是否跳过错误继续处理
    
    返回:
        list: 预处理结果列表
    """
    results = []
    
    for i, inp in enumerate(input_list):
        result = preprocess(
            input_data=inp,
            input_type=input_type,
            output_dir=output_dir,
            nproc=nproc,
            charge=charge,
            multiplicity=multiplicity,
            method=method,
            xtb_path=xtb_path,
            keep_temp=keep_temp
        )
        results.append(result)
        
        if not result['success'] and not skip_errors:
            break
    
    return results


# ============ 导出函数 ============

__all__ = [
    'preprocess',
    'batch_preprocess',
    'sqrt_norm',
    'detect_functional_groups',
    'process_smiles',
    'DEFAULT_XTB_PATH',
    'DEFAULT_NPROC',
    'DEFAULT_CHARGE',
    'DEFAULT_MULTIPLICITY',
    'DEFAULT_METHOD',
]